# Generated by Django 6.1 on 2026-09-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ('voting', '0008_voterreceipt_anonymize_vote'),
]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(choices=[('NORMAL', 'Normal Election'), ('RUNOFF', 'Runoff')], default='NORMAL', max_length=20),
        ),
    ]
