# Generated by Django 6.1 on 2026-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_candidate_campus_alter_voterreceipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='election_logos/'),
        ),
        migrations.AlterField(
            model_name='voterreceipt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
