# Generated by Django 6.1 on 2026-10-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_election_logo_alter_voterreceipt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
